name: Test Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python with uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.11"

      - name: Install project with test dependencies
        run: uv pip install .[test]

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report --fail-under=92
